---
title: "Useful Code"
author: "Madison Arnsbarger"
date: "5/31/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R
#### Load SPSS (.sav) data
```{r SPSS_Data, eval=FALSE, echo=TRUE}
library(foreign)
setwd("~/.../")
file.choose("data.sav")
df <- read.spss("data.sav", to.data.frame = TRUE) # class(df) is data.frame

```

#### Remove all numbers from a string
```{r gsub, eval=FALSE, echo=TRUE}
df$string_variable <- gsub("\\d+", "", df$string_variable)
```

#### Query database
```{r Query_Database, eval=FALSE, echo=TRUE}
source(file="pg_connect.R") # make secure connection to database
df <- dbReadTable(con, c("schema-name","table-name"), row.name = FALSE)
```

#### Query single variable
```{r Query_var, eval=FALSE, echo=TRUE}
variable <- dbGetQuery(con,
                       paste("SELECT", column_name_quoted,
                             "FROM", schema_table_name))
```

#### Basic Function 
```{r Functions}
function_name <- function(x,y){
  print(x*y)
}

function_name(2,3)
```

#### setwd()
If your working directory changes when you knit...
```{r setwd(), eval=FALSE}
if (interactive()){
    data_location <- 'data/project/original/my.csv'
} else {
    data_location <- '../../data/project/original/my.csv'
}
```

#### Convert empties to NA
```{r empties, eval=FALSE}
data[data=='' | data==' ' | data=="Missing"] <- NA
```


#### Importing Shapefiles: rgdal::readOGR
```{r}
arlington_fireboxes <- readOGR("data/shapefiles/fireboxes", "Fireboxes")
plot(arlington_fireboxes)
```


#### Connect to database
```{r database, eval=FALSE}
library(DBI)
library(RPostgreSQL)
library(sdalr)

con <- sdalr::con_db(dbname = "arlington", user = 'your_pid', pass = 'your_password')

q <- sprintf('SELECT * FROM %s;', "schema.table")
df <- dbGetQuery(con, q)
```
#### Convert shapefile to dataframe (fortify while maintaining other info!)
```{r shp_to_df, eval=FALSE}
# Get ACS data
acsPov <- <some acs data with block group id's and population counts for Roanoke>

# Get GIS data
Roanoke <- block_groups("Virginia", c("Roanoke County"))

# convert Roanoke block groups to a dataframe
Roanoke@data$id = rownames(Roanoke@data)
Roanoke.points = fortify(Roanoke, region="id")
Roanoke.df = left_join(Roanoke.points, Roanoke@data, by="id")
# merge with ACS data
RoanokeACS <- left_join(acsPov, Roanoke.df, by = c("geoID"="GEOID"))

names(map_data)
# [1] "GEO.id2"   "HD01_VD01" "HD01_VD05" "long"      "lat"       "order"     "hole"      "piece"
# [9] "id"        "group"     "STATEFP"   "COUNTYFP"  "TRACTCE"   "BLKGRPCE"  "NAMELSAD"  "MTFCC"    
# [17] "FUNCSTAT"  "ALAND"     "AWATER"    "INTPTLAT"  "INTPTLON"
```
